---
title: "reading exercise 6.6"
format: html
editor: visual
---

# Problem 4 (Medium): Generate the code to convert the following data frame to wide format.

A tibble: 4 × 6
  grp   sex   meanL   sdL meanR    sdR
  <chr> <chr> <dbl> <dbl> <dbl>  <dbl>
1 A     F     0.225 0.106 0.34  0.0849
2 A     M     0.47  0.325 0.57  0.325 
3 B     F     0.325 0.106 0.4   0.0707
4 B     M     0.547 0.308 0.647 0.274 

## Hint: use pivot_longer() in conjunction with pivot_wider().

A tibble: 2 × 9
  grp   F.meanL F.meanR F.sdL  F.sdR M.meanL M.meanR M.sdL M.sdR
  <chr>   <dbl>   <dbl> <dbl>  <dbl>   <dbl>   <dbl> <dbl> <dbl>
1 A       0.225    0.34 0.106 0.0849   0.47    0.57  0.325 0.325
2 B       0.325    0.4  0.106 0.0707   0.547   0.647 0.308 0.274


```{r}
library(tidyverse)

grp <- c("A", "A", "B", "B")
sex <- c("F", "M", "F", "M")
meanL <- c(0.255, 0.47, 0.325, 0.547)
sdL <- c(0.106, 0.325, 0.106, 0.308)
meanR <- c(0.34, 0.57, 0.4, 0.647)
sdR <- c(0.0849, 0.325, 0.0707, 0.274)

df <- data.frame(grp, sex, meanL, sdL, meanR, sdR)
df
```

```{r}
df_wide <- df |>
  pivot_longer(cols = c(meanL, sdL, meanR, sdR),
               names_to = "measure",
               values_to = "value") |>
  pivot_wider(names_from = c(sex, measure),
              values_from = value,
              names_sep = ".")
df_wide
```

