---
title: "w12l2_act.qmd"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(leaflet)
library(tidycensus)
library(RColorBrewer)
library(sf)

# Coordinates
nyc_311_xy <- read_csv("https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$select=x_coordinate_state_plane,y_coordinate_state_plane&$where=complaint_type=%27Missed%20Collection%27%20AND%20date_trunc_ymd(created_date)=%272021-10-01%27&$limit=400")

# Rodent Data
nyc_311_rodent <- read_csv("https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$where=complaint_type=%27Rodent%27%20AND%20date_trunc_ymd(created_date)=%272022-04-04%27") |>
  filter(!is.na(longitude)) |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 3857) 
nyc_311_litter <- read_csv("https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$where=complaint_type=%27Litter%20Basket%20Complaint%27%20AND%20date_trunc_ymd(created_date)=%272022-04-04%27") |>
  filter(!is.na(longitude)) |>
  st_as_sf(coords = c("longitude", "latitude"), crs = 3857) 
```

```{r}
nyc_311_xy <- nyc_311_xy |>
  st_as_sf(coords = c("x_coordinate_state_plane", "y_coordinate_state_plane"), crs = 2263) |>
  st_transform(crs = 4326)
  
leaflet() |>
  setView(lat = 40.7, lng = -74.0, zoom = 11) |> 
  addProviderTiles("Esri.NatGeoWorldMap") |>
  addCircleMarkers(data = nyc_311_rodent,
                   fillColor = "purple",
                   fillOpacity = 0.5,
                   stroke = FALSE)
```

```{r}
pal_numeric <- colorNumeric(palette = "plasma",
                            domain = nyc_311_rodent$unique_key)
leaflet() |>
  setView(lat = 40.7, lng = -74.0, zoom = 11) |> 
  addProviderTiles("Esri.NatGeoWorldMap") |>
  addCircleMarkers(data = nyc_311_rodent,
                   fillColor = ~pal_numeric(unique_key),
                   fillOpacity = 0.5,
                   stroke = FALSE) |>
  addLegend(data = nyc_311_rodent,
             title = "Reports of Rat Sightings in NYC, 2022", 
             pal = pal_numeric, 
             values = ~unique_key)
```

